landing/urls.py
from django.urls import path
from landing.views import *

app_name = 'landing'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('list-pasien/', list_pasien, name='listPasien'),
    path('menu-pasien/', menu_pasien, name='menuPasien'),
    path('menu-pasien/edit/<int:pk>', edit_pasien, name='editPasien'),
    path('show-pasien/<int:pk>', show_pasien, name='showPasien'),
    path('show-dokter/', show_dokter, name='showDokter'),
    path('change-status/', change_status, name='changeStatus'),
    path('modif-hasil/', modif_hasil, name='modifHasil'),
    path('show_json_konseling_dokter/', show_json_konseling_dokter, name='show_json_konseling_dokter'),
    path('menu-pasien/set-konseling/<int:pk>', ubah_status, name='ubah_status'),
    path('menu-pasien/delete/<int:pk>', hapus, name='hapus'),   
]

operasi/urls.py
from django.urls import path
from operasi.views import *

app_name = 'operasi'

urlpatterns = [
    path('', show_jadwal_operasi, name='show_jadwal_operasi'),
    path('json/', jadwal_operasi_json, name='jadwal_operasi_json'),
    path('add/', add_jadwal_operasi, name='add_jadwal_operasi'),
    path('deleteweb/<int:pk>', delete_operasi, name='delete_operasi'),
    path('pasien/', list_pasien_json, name='list_pasien_json'),
    path('delete/<int:pk>', delete_operasi_flutter, name='delete_operasi_flutter'),
]

pelayananApotek/urls.py
from django.urls import path
from pelayananApotek.views import show_obat
from pelayananApotek.views import add_obat
from pelayananApotek.views import show_obat_json
from pelayananApotek.views import change_status
from pelayananApotek.views import delete_obat
from pelayananApotek.views import change_status_obat
from pelayananApotek.views import show_patient_json
from pelayananApotek.views import show_patient
from pelayananApotek.views import show_obat_selain_apoteker
from pelayananApotek.views import delete_obat_flutter
from pelayananApotek.views import change_status_obat_flutter
from pelayananApotek.views import change_status_pasien_flutter

app_name = 'pelayananApotek'

urlpatterns = [
    path('', show_obat, name = 'show_obat'),
    path('add_obat/', add_obat, name = 'add_obat'),
    path('json/', show_obat_json, name='show_obat_json'),
    path('delete_obat/<int:pk>', delete_obat, name='delete_obat'),
    path('change_status/<int:pk>', change_status, name='change_status'),
    path('change_status_obat/<int:pk>', change_status_obat, name='change_status_obat'),
    path('show_patient_json/', show_patient_json, name='show_patient_json'),
    path('show_patient/', show_patient, name='show_patient'),
    path('apotek/', show_obat_selain_apoteker, name='show_obat_selain_apoteker'), 
    path('delete_obat_flutter/<int:pk>', delete_obat_flutter, name='delete_obat_flutter'),
    path('change_status_obat_flutter/<int:pk>', change_status_obat_flutter, name='change_status_obat_flutter'),
    path('change_status_pasien_flutter/<int:pk>', change_status_pasien_flutter, name='change_status_pasien_flutter'),
]

pelayananDokter/urls.py
from django.urls import path
from pelayananDokter.views import addKeluhan, tembakKeluhan, show_log,doctorReady

app_name = 'pelayananDokter'

urlpatterns = [
    path('', addKeluhan, name='addKeluhan'),
    path('add/', tembakKeluhan, name='tembakKeluhan'),
    path('show_log/', show_log, name='showLog'),
    path('show_doc/', doctorReady, name='showDoc'),
]

pelayananKonseling/urls.py
from django.urls import path
from .views import *

app_name = 'pelayananKonseling'

urlpatterns = [
    path('', addKonseling, name='addKonseling'),
    path('tembakDBAjax/', tembakDBAjax, name='tembakDBAjax'),
    path('show_json_konseling/', show_json_konseling, name='show_json_konseling'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('operasi/', include("operasi.urls")),
    path('pelayananDokter/', include('pelayananDokter.urls')),
    path('pelayananKonseling/', include('pelayananKonseling.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('pembayaran/', include('pembayaran.urls')),
    path('pelayananApotek/', include('pelayananApotek.urls')),
]

landing/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Landing(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    is_patient = models.BooleanField(null=True, blank=True)
    is_doctor = models.BooleanField(null=True, blank=True, default=False)
    is_apotek = models.BooleanField(null=True, blank=True, default=False)
    is_admin = models.BooleanField(null=True, blank=True, default=False)  
    doctorReady = models.BooleanField(null=True, default=False)   
    username = models.CharField(max_length=30, default='-') 


    def __str__(self):
        return self.username

landing/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login
from django.http import HttpResponseRedirect
import datetime
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from landing.models import Landing
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from django.contrib.auth.models import User
from pelayananDokter.models import Layan
from django.core import serializers
from django.http.response import JsonResponse, HttpResponse, HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from pelayananKonseling.models import PelayananKonseling


def index(request):
    masuk = None
    statusAdmin = False
    statusApotek = False
    statusDokter = False
    statusPatient = False
    if request.user.username != "":
        masuk = getUser(request.user)
        statusAdmin = isAdmin(masuk)
        statusApotek = isApotek(masuk)
        statusDokter = isDoctor(masuk)
        statusPatient = isPatient(masuk)
    context = {
    'statPat' : statusPatient,
    'statDok' : statusDokter,
    'statApo' : statusApotek,
    'statAdm' : statusAdmin,
    'user': request.user.username,
    'nama': 'Yudi Putra Sabri',
    'npm': 2106706123,
    }
    return render(request, 'index.html', context)

@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("landing:index")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            masuk = getUser(request.user)
            statusAdmin = isAdmin(masuk)
            statusApotek = isApotek(masuk)
            statusDokter = isDoctor(masuk)
            statusPatient = isPatient(masuk)
                
            return JsonResponse({
            "status": True,
            'statPat' : statusPatient,
            'statDok' : statusDokter,
            'statApo' : statusApotek,
            'statAdm' : statusAdmin,
            "message": "Successfully Logged In!"
            # Insert any extra data if you want to pass data to Flutter
            }, status=200)
        else:
            messages.info(request, 'Username atau Password salah!')
            return JsonResponse({
            "status": False,
            "message": "Failed to Login, check your email/password."
            }, status=401)
    context = {}
    return render(request, 'login.html', context)


@csrf_exempt
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        uname = request.POST.get('username')
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            getUs = User.objects.get(username=uname)
            Landing.objects.create(user=getUs, is_patient=True, username=getUs.username)
            return JsonResponse({
            "status": True,
            "message": "Successfully Register!"
            # Insert any extra data if you want to pass data to Flutter
            }, status=200)
        else :
            return JsonResponse({
            "status": False,
            "message": "Failed to Register."
            }, status=401)
            
    
    context = {'form':form}
    return render(request, 'register.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('landing:index'))
    response.delete_cookie('last_login')
    return JsonResponse({
            "status": True,
            "message": "Successfully Register!"
            # Insert any extra data if you want to pass data to Flutter
            }, status=200)

def isPatient(masuk):
    if masuk.is_patient:
        return True
    return False

def isDoctor(masuk):
    if masuk.is_doctor:
        return True
    return False

def isApotek(masuk):
    if masuk.is_apotek:
        return True
    return False

def isAdmin(masuk):
    if masuk.is_admin:
        return True
    return False

def getUser(test):
    return Landing.objects.get(user=test.pk)

def list_pasien(request):
    data = Landing.objects.get(user=request.user)
    if data.is_doctor:
        data = Layan.objects.filter(hasilPeriksa="-",dokter=data)
        return HttpResponse(serializers.serialize('json', data), content_type='application/json')
    else:
        return HttpResponseNotFound("You Don't Belong Here")
        
@login_required(login_url='../../login/')
def menu_pasien(request):
    data = Landing.objects.get(user=request.user)
    if data.is_doctor:
        statusAdmin = False
        statusApotek = False
        statusDokter = False
        statusPatient = False
        if request.user.username != "":
            statusAdmin = isAdmin(data)
            statusApotek = isApotek(data)
            statusDokter = isDoctor(data)
            statusPatient = isPatient(data)
        context = {
            'statPat' : statusPatient,
            'statDok' : statusDokter,
            'statApo' : statusApotek,
            'statAdm' : statusAdmin,
            'ready' : data.doctorReady,
        }
        return render(request, 'menuPasien.html', context)
    else:
        return HttpResponseNotFound("You Don't Belong Here")  

def edit_pasien(request, pk):
    data = Landing.objects.get(user=request.user)
    dataPasien = Landing.objects.filter(pk=pk)
    if data.is_doctor:
        statusAdmin = False
        statusApotek = False
        statusDokter = False
        statusPatient = False
        if request.user.username != "":
            statusAdmin = isAdmin(data)
            statusApotek = isApotek(data)
            statusDokter = isDoctor(data)
            statusPatient = isPatient(data)
        context = {
            'statPat' : statusPatient,
            'statDok' : statusDokter,
            'statApo' : statusApotek,
            'statAdm' : statusAdmin,
            'pasien'  : dataPasien,
            'masuk' : pk,
        }
    return render(request, 'editPasien.html', context)

def show_pasien(request, pk):
    data = Landing.objects.get(user=request.user)
    if data.is_doctor:
        data = Layan.objects.filter(pk=pk)
        return HttpResponse(serializers.serialize('json', data), content_type='application/json')
    else:
        return HttpResponseNotFound("You Don't Belong Here")  

def show_dokter(request):
    data = Landing.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', data), content_type='application/json')

@csrf_exempt
def change_status(request):
    task = Landing.objects.get(user=request.user)
    task.doctorReady = not (task.doctorReady)
    task.save()
    return JsonResponse({"instance": "Proyek Dibuat"},status=200)

@csrf_exempt
def modif_hasil(request):
    if request.method == 'POST':
        desc = request.POST.get('hasil')
        peka = request.POST.get('peka')
        dataMasuk = Layan.objects.get(pk=int(peka))
        dataMasuk.hasilPeriksa = desc
        dataMasuk.status = not dataMasuk.status
        dataMasuk.save()
        return JsonResponse({
            "status": True,
            "message": "Successfully Edited!"
            # Insert any extra data if you want to pass data to Flutter
            }, status=200)

@login_required(login_url='../../login/')
def show_json_konseling_dokter(request):
    data = PelayananKonseling.objects.all()
    return HttpResponse(serializers.serialize('json', data), content_type='application/json')

def ubah_status(request, pk):
    data = PelayananKonseling.objects.get(pk=pk)
    data.status_konseling = not data.status_konseling
    data.save()
    return redirect('landing:menuPasien')

def hapus(request, pk):
    data = PelayananKonseling.objects.get(id=pk)
    data.delete()
    return JsonResponse({'status': 'success'})

landing/templates/editPasien.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Edit Pasien</title>
{% endblock meta %}

{% block content %}
<p class="hidden" id="identifier">{{masuk}}</p>
<div class=" p-4 bg-gray-300 h-fit rounded-2xl my-2">
    <div class=""id="inside">
    </div>
</div>
{% endblock content %}

{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    let peka = $('#identifier').text();
    function loadData() {
        let tab= "";
        $.ajax({
            url: `/show-pasien/${peka}`,
            type: "GET",
            dataType: "json",
            success: function(resp){  
                for (let i of resp){
                    let status = i.fields.status;
                    let type = i.pk;

                    if (!status){
                        tab +=`
                        <div class="" id="${i.pk}div">
                            <div id="${i.pk}" class="bg-white rounded-2xl p-8 flex w-fit flex-col gap-2 hover:drop-shadow-2xl transition duration-300 ease-in-out">
                                <p class="text-center text-xl font-semibold">${i.fields.username}</p>
                                <p class="text-center text-xs">${i.fields.tanggal_janji.slice(0,10)} ${i.fields.tanggal_janji.slice(11,19)} </p>
                                <div class="flex m-2 p-2 justify-center">
                                    <div>
                                        <div class="transition-opacity bg-gray-600 bg-opacity-10 rounded-2xl p-2">
                                        <p class="break-all">${i.fields.keluhan}</p>
                                        </div>
                                        <p class="break-all flex justify-center">${i.fields.noHP}</p>
                                    </div>
                                </div>

                                <form method="post" id="tembakDB" class="${i.pk}">
                                    {% csrf_token %}
                                    <div class="">
                                        <table>
                                                <div class="flex gap-4">
                                                    <tr>Hasil Periksa: </tr>
                                                    <tr><input class="rounded-2xl border-2 border-black" style="width: 100%;height: 60px;" type="text" name="hasil" placeholder="Hasil Pemeriksaan" class="form-control" id="hasil"></tr>
                                                </div>
                    
                                        </table>
                                    </div>
                                    
                                    <div class="flex gap-4 mt-4 justify-center">
                                            <input class=" bg-yellow-300 rounded-2xl p-1 text-black text-lg font-bold" type="submit" name="submit" value="Kirim!"/>
                                    </div>
                                </form>
                            </div>
                        </div>
                        `
                    };
                
                };
                $('#inside').append(tab);
            },
            error: function(resp){
                console.log('Error?');
            }
        })
    };
</script>
<script src="{% static '/editPasien.js' %}"></script>

{% endblock script %}

landing/templates/index.html
{% extends 'base.html' %}

{% block meta %}
{% load static %}
<title>UI HealCast</title>
{% load tailwind_tags %}
{% tailwind_css %}
{% endblock meta %}

{% block content %}
<div class=" rounded-xl bg-[url(hero.jpg)] bg-cover object-cover">
	
  <div class=" flex flex-col gap-8 p-20">
    <h1 class="lg:text-2xl text-lg  pl-2 bg-yellow-400 w-fit rounded-2xl p-2 text-black no-underline font-bold">UI Health Care</h1>
    <div class=" bg-slate-600 bg-opacity-40 w-fit rounded-2xl">
      <p class="text-white p-10 text-xs lg:text-xl md:text-lg">Buat Janji Mudah dan Cepat</br>
        Layanan Booking Dokter Terbaik di Indonesia</p>
    </div>
    <div class="">
      <a href="{% url 'pelayananDokter:addKeluhan' %}">
        <button type="button"
            class="focus:outline-none font-bold text-black bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-yellow-300  rounded-lg lg:text-sm text-xs p-2 dark:focus:ring-yellow-900">
          Daftar Berobat
        </button>
      </a>
      <a href="{% url 'pelayananKonseling:addKonseling' %}">
        <button type="button"
            class="focus:outline-none font-bold text-black bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-yellow-300 rounded-lg lg:text-sm text-xs p-2 dark:focus:ring-yellow-900">
          Daftar Konseling
        </button>
      </a>
    </div>
  </div>
		
	<!-- <div class="row-span-6 col-span-2">
		<img class="object-cover h-full w-full rounded-r-lg" src='{% static "/test1.svg" %}' alt="home"/>
	</div> -->

</div>

{% endblock content %}


{% block script %}
<script>
</script>
{% endblock script %}

landing/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Masuk</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    {% load static tailwind_tags %}
    {% tailwind_css %}
    {% load static %}
    {% include "navbarMod.html" %}
    <div class=" bg-slate-200">
        <div class ="h-screen flex items-center justify-center shadow-2xl">
            <div class="">
                <div class="rounded-4 bg-yellow-300 p-5 mt drop-shadow-2xl">

                    <div class=" bg-black p-3 rounded-2xl w-full m-2 flex justify-center">
                        <h1 class="font-bold text-white">Login First!</h1>
                    </div>

                    <form method="POST" action="">
                        {% csrf_token %}
                        <table>
                            <tr>
                                <div class="p-2 w-full justify-center flex ">
                                    <input class="rounded-2xl p-2 flex justify-center" type="text" name="username" placeholder="Username" class="form-control">
                                </div>
                            </tr>    
                            <tr>
                                <p></p>
                                <div class="p-2 w-full justify-center flex ">
                                    <input class="rounded-2xl p-2" type="password" name="password" placeholder="Password" class="form-control">
                                </div>
                            </tr>

                            {% if messages %}
                            {% for message in messages %}
                            <div class=" m-2 rounded-lg">
                                <p class="">Note : {{ message }}</p>
                            </div>
                            {% endfor %}
                            {% endif %} 
                
                            <tr>
                                <div class="justify-center flex cursor-pointer">
                                    <div class="bg-white w-fit p-1 rounded-2xl">
                                        <input class="cursor-pointer text-black text-xl font-bold" type="submit" value="Masuk">
                                    </div>
                                </div>
                            </tr>
                        </table>
                    </form>
                
                    <div class="flex justify-center">
                        <div class="rounded-full bg-red-500 p-1 m-2 w-fit cursor-pointer">
                            <a class="text-white font-bold" href="{% url 'landing:register' %}">Buat Akun</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<script src="{% static '/toggleNav.js' %}"></script>

landing/templates/menuPasien.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Menu Pasien</title>
<link rel="stylesheet" href="{% static '/slider.css' %}" />
{% endblock meta %}

{% block content %}
<div class=" p-4 bg-gray-300 h-fit rounded-2xl ">
    <p class="font-bold text-2xl">Ketersediaan Dokter</p class="font-bold text-2xl">
    <div class="w-1/4">
        <label class="toggle m-2">
            <input type="checkbox"  id="checkedDokter"/>
            <span onclick="changeStatus()" class="slider round"></span>
            <span class="onoff"></span>
        </label>
    </div>
</div>


<div class=" p-4 bg-gray-300 h-fit rounded-2xl my-2">
    <p class="font-bold text-2xl">Layanan Dokter</p class="font-bold text-2xl">
    <div class="grid lg:grid-cols-4 md:grid-cols-3 gap-5 mt-8 sm:mt-5" id="listPat">
    </div>
</div>

<div class=" p-4 bg-gray-300 h-fit rounded-2xl ">
    <p class="font-bold text-2xl">Layanan Konseling</p class="font-bold text-2xl">
    <div class="grid lg:grid-cols-4 md:grid-cols-3 gap-5 mt-8 sm:mt-5" id="listKonseling">
    </div>
</div>

{% endblock content %}



{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static '/menuPasien.js' %}"></script>

{% endblock script %}

landing/templates/navbarMod.html
<nav class="flex items-center justify-between flex-wrap bg-yellow-300 bg-opacity-75 p-1 fixed w-full z-10 top-0">
    <div class="flex items-center flex-shrink-0 text-white mr-6 h-6">
        <a href="{% url 'landing:index' %}">
            <span><img class="mr-3 h-6 sm:h-9" src="https://user-images.githubusercontent.com/112607944/199466373-48ea608a-8d42-4a07-a41a-a840cd8fbb76.png
            " alt="Logo"></span>
        </a>
    </div>

    <div class="block lg:hidden">
        <button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
    </div>

    <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block pt-6 lg:pt-0" id="nav-content">
        <ul class="list-reset lg:flex justify-end flex-1 items-center">
            <li class="mr-3">
                <!-- <a class="inline-block py-2 px-4 text-gray-600 no-underline hover:text-gray-200 no-underline" href="#">Pelayanan</a> -->
      <div class="">
        <div class="flex items-center ">
          <button class="inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline px-4 rounded flex items-center" id="menu-btn">Pelayanan
            <?xml version="1.0" ?><svg height="48" viewBox="0 0 48 48" width="40" xmlns="http://www.w3.org/2000/svg"><path d="M14 20l10 10 10-10z"/><path d="M0 0h48v48h-48z" fill="none"/></svg>
          </button>
        </div>
        <div class="bg-white hidden flex-col rounded mt-1 p-2 text-sm w-32 absolute" id="dropdown">
            <a href="{% url 'pelayananDokter:addKeluhan' %}" class="px-2 py-1 hover:bg-blue-300 rounded">Dokter</a>
            <a href="{% url 'operasi:show_jadwal_operasi' %}" class="px-2 py-1 hover:bg-blue-300 rounded">Operasi</a>
            <a href="{% url 'pelayananKonseling:addKonseling' %}" class="px-2 py-1 hover:bg-blue-300 rounded">Konseling</a>
        </div>
      </div>
            </li>
            <li class="mr-3">
                {% if is_apotek %}
                <a class="inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4" href="{% url 'pelayananApotek:show_obat' %}">Apotek</a>
                {% else %}
                <a class="inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4" href="{% url 'pelayananApotek:show_obat_selain_apoteker' %}">Apotek</a>
                {% endif %}
            </li>
            <li class="mr-3">
                <a class="inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4" href="#">Pembayaran</a>
            </li>
            <li class="mr-3">
                <!-- pas udah masuk, didelete terus diganti tampilan -->
                <a class="inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4" id="account" href="{% url 'landing:login' %}">Masuk</a>
            </li>
        </ul>
    </div>
</nav>

landing/templates/register.html
{% load static tailwind_tags %}
{% tailwind_css %}
{% load static %}
<title>Registrasi Akun</title>
<div class="">
  {% include "navbarMod.html" %}
  <div class="flex justify-center mt-[15%]">
    <div class=" bg-yellow-300 rounded-2xl p-3">
      <div class="text-4xl font-bold text-black text-center">Register</div>
      <div class="lg:w-64 mt-6">
        <form method="POST" action="">
          {% csrf_token %}
          <div>
            <label class="block">
              <span
                class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-500"
              >
                {{ form.username.label }}
              </span>
              <input
                type="text"
                name="username"
                class="mt-1 px-3 py-2 bg-[#2d3748] border shadow-sm border-slate-600 placeholder-slate-400 focus:outline-none focus:border-[#4a9ebd] focus:ring-[#4a9ebd] block w-full rounded-md sm:text-sm focus:ring-1 text-slate-300"
                placeholder="Username"
              />
              {% if form.username.errors %}
              <div class="mt-2 text-red-500 text-sm">
                {{form.username.errors }}
              </div>
              {% endif %}
            </label>
            <label class="block mt-1">
              <span
                class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-500"
              >
                {{ form.password1.label }}
              </span>
              <input
                type="password"
                name="password1"
                class="mt-1 px-3 py-2 bg-[#2d3748] border shadow-sm border-slate-600 placeholder-slate-400 focus:outline-none focus:border-[#4a9ebd] focus:ring-[#4a9ebd] block w-full rounded-md sm:text-sm focus:ring-1 text-slate-300"
                placeholder="Password"
              />
              {% if form.password1.errors %}
              <div class="mt-2 text-red-500 text-sm">
                {{form.password1.errors}}
              </div>
              {% endif %}
            </label>

            <label class="block mt-1">
              <span
                class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-500"
              >
                {{ form.password2.label }}
              </span>
              <input
                type="password"
                name="password2"
                class="mt-1 px-3 py-2 bg-[#2d3748] border shadow-sm border-slate-600 placeholder-slate-400 focus:outline-none focus:border-[#4a9ebd] focus:ring-[#4a9ebd] block w-full rounded-md sm:text-sm focus:ring-1 text-slate-300"
                placeholder="Confirm Password"
              />
              {% if form.password2.errors %}
              <div class="mt-2 text-red-500 text-sm">
                {{ form.password2.errors }}
              </div>
              {% endif %}
            </label>
          </div>
          <button
            type="submit"
            name="submit"
            class="rouned-lg bg-black w-full bg-opacity-80 h-10 text-slate-100 mt-4 font-bold"
          >
            Daftar
          </button>
        </form>
        <div class="mt-4 text-center text-black font-semibold">
          Sudah punya akun? 
          <a
            href="{% url 'landing:login' %}"
            class="underline underline-offset-2"
          >
            Masuk
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="{% static '/toggleNav.js' %}"></script>